#[derive(Clone, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IndependentApproveRecordV1 {
    pub operation_id: String,
    pub browser_request: ManagementRequestV2,
    pub browser_request_digest_sha256: String,
    pub phase: IndependentApprovePhaseV1,
    pub finish_request: AuthorityRequestV1,
    pub finish_exchange: Option<SignedAuthorityExchangeV1>,
    pub current_request: Option<AuthorityRequestV1>,
    pub current_exchange: Option<SignedAuthorityExchangeV1>,
    pub current_observed_at_epoch_s: Option<u64>,
    pub approval_request_json: Option<String>,
    pub approval_request: Option<AuthorityRequestV1>,
    pub approval_key_id: Option<String>,
    pub approval_key_fingerprint: Option<String>,
    pub approval_public_key_hex: Option<String>,
    pub approval_exchange: Option<SignedAuthorityExchangeV1>,
    pub pre_final_request_json: Option<String>,
    pub pre_final_request: Option<EndpointIndependentRevocationPreFinalRequestV1>,
    pub pre_final_response_json: Option<String>,
    pub pre_final_response: Option<ManagementProjectionV2>,
    pub pre_final_trust: Option<IndependentProjectionTrustPinV1>,
    pub reservation_current_request: Option<AuthorityRequestV1>,
    pub reservation_current_exchange: Option<SignedAuthorityExchangeV1>,
    pub reservation_current_observed_at_epoch_s: Option<u64>,
    pub execution_reserve_request_json: Option<String>,
    pub execution_reserve_request: Option<EndpointRevocationExecutionReserveRequestV1>,
    pub execution_reservation_json: Option<String>,
    pub execution_reservation: Option<EndpointRevocationExecutionReservationV1>,
    pub execution_reservation_trust: Option<IndependentReservationTrustPinV1>,
    pub final_request_json: Option<String>,
    pub final_request: Option<AuthorityRequestV1>,
    pub final_exchange: Option<SignedAuthorityExchangeV1>,
    pub finalize_request_json: Option<String>,
    pub finalize_request: Option<EndpointIndependentRevocationFinalizeRequestV1>,
    pub response_key_id: String,
    pub response_public_key_hex: String,
    pub response_minimum_generation: u64,
    pub response_json: Option<String>,
    pub response: Option<ManagementProjectionV2>,
    pub expires_at_epoch_s: u64,
    pub updated_at_epoch_s: u64,
}

pub(super) struct IndependentApproveResume {
    pub selected_identity: SignedAuthorityExchangeV1,
    pub selected_begin: SignedAuthorityExchangeV1,
    pub lookup: crate::actor_options_state_types::ActorPreparedLookupV1,
    pub actor_projection: ManagementProjectionV2,
    pub approval: Box<IndependentApproveRecordV1>,
}
